version: '3.8'

services:
  # 你的个人网站
  my-website:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  # 替换为兼容的 Todo 应用（示例：TodoMVC）
  todo-app:
    image: tastejs/todomvc  # 使用官方 TodoMVC 镜像
    ports:
      - "8081:80"
    restart: unless-stopped