version: '3.8'
services:
  personal-website:
    build: .          
    ports:
      - "8081:80"     
    restart: always


  todo-app:
    image: docker.io/dockersamples/static-site  
    ports:
      - "8082:80"     
    restart: always
