version: '3.8'

services:
  my-website:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  # 使用 `docker/getting-started` 镜像（官方示例，含 Todo 功能）
  todo-app:
    image: docker/getting-started
    ports:
      - "8081:80"
    restart: unless-stopped