version: '3.8'
services:
  personal-website:
    build: .          # 使用当前目录的 Dockerfile
    ports:
      - "8080:80"     # 个人网站访问端口: 8080
    restart: always


  todo-app:
    image: docker.io/dockersamples/static-site  # 替换为真实存在的公共镜像
    ports:
      - "3000:80"     # Todo App 访问端口: 3000
    restart: always