version: '3.8'

services:
  # 你的个人网站
  my-website:
    build: .
    ports:
      - "8080:80"  # 访问 http://localhost:8080
    restart: unless-stopped

  # Todo 应用（示例：使用现成的 Todo 镜像）
  todo-app:
    image: alexwhen/docker-2048  # 示例，可替换为其他 Todo 镜像
    ports:
      - "8081:80"  # 访问 http://localhost:8081
    restart: unless-stopped